[tool.black]
line-length = 120

[[tool.mypy.overrides]]
module = "setuptools.*"
follow_imports = "skip"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "networkx.*"
follow_imports = "skip"
ignore_missing_imports = true
