name: CI

on:
  pull_request:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        mode:
          - "installed"
          - "source-code"
      fail-fast: false

    container:
      image: python:${{ matrix.python-version }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov build
          apt update
          apt install -y bison

      - name: build
        if: matrix.mode == 'installed'
        run: |
          python -m build

      - name: install
        if: matrix.mode == 'installed'
        run: |
          pip install dist/*.whl

      - name: pytest
        run: |
          if [ "${{ matrix.mode }}" = "installed" ]
          then
            pytest --import-mode=importlib
          else
            pytest --cov=neologism --cov-fail-under=100
          fi

  style-check:
    runs-on: ubuntu-latest

    container:
      image: python:3

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          pip install black

      - name: black
        run: |
          black --check --diff .

  doc-check:
    runs-on: ubuntu-latest

    container: python:3
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme

      - name: sphinx-build
        run: |
          sphinx-build -W -b html docs/source/ docs/build/html
