name: CI

on:
  pull_request:
  push:

jobs:
  self-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
      fail-fast: false

    container:
      image: python:${{ matrix.python-version }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          pip install -r requirements.txt
          pip install pytest
          apt update
          apt install -y bison

      - name: pytest
        run: |
          python -m pytest

  style-check:
    runs-on: ubuntu-latest

    container:
      image: python:3

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          pip install black

      - name: black
        run: |
          black --check --diff .
