name: CI

on:
  pull_request:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        mode:
          - "installed"
          - "source-code"
      fail-fast: false

    container:
      image: python:${{ matrix.python-version }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          pip install poetry
          apt update
          apt install -y bison

      - name: Install (source-code mode)
        if: matrix.mode == 'source-code'
        run: poetry install

      - name: Build & install wheel (installed mode)
        if: matrix.mode == 'installed'
        run: |
          poetry build
          pip install dist/*.whl pytest

      - name: pytest
        run: |
          if [ "${{ matrix.mode }}" = "installed" ]
          then
            pytest -p no:cov --import-mode=importlib
          else
            poetry run pytest --cov-fail-under=100
          fi

  style-check:
    runs-on: ubuntu-latest

    container:
      image: python:3

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          pip install poetry
          poetry install

      - name: black
        run: poetry run black --check --diff .

  linter:
    runs-on: ubuntu-latest

    container:
      image: python:3

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          pip install poetry
          poetry install

      - name: mypy
        run: poetry run mypy .

  doc-check:
    runs-on: ubuntu-latest

    container:
      image: python:3

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          pip install poetry
          poetry install

      - name: sphinx-build
        run: poetry run sphinx-build -W -b html docs/source/ docs/build/html
