name: Release

on:
  workflow_dispatch:
    inputs:
      is_test_release:
        description: "is_test_release (true/false): If set to true, uploads to test.pypi.org and does not create a GitHub Release."
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    container:
      image: python:3

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          pip install -r requirements.txt
          pip install pytest build twine
          apt update
          apt install -y bison

      - name: build
        run: |
          python -m build

      - name: install
        run: |
          pip install dist/*.whl

      - name: self-test
        run: |
          pytest --import-mode=importlib

      - name: upload package (test.pypi.org)
        if: github.event.inputs.is_test_release == 'true'
        run: |
          twine upload -r testpypi dist/* -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: upload package (pypi.org)
        if: github.event.inputs.is_test_release == 'false'
        run: |
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish GitHub Release
        if: github.event.inputs.is_test_release == 'false'
        run: |
          VERSION=$(cat VERSION | tr -d "\n")
          echo ${VERSION} > /tmp/message

          hub release create \
            --file /tmp/message \
            --attach dist/neologism-${VERSION}.tar.gz \
            ${VERSION}
