name: Release

on:
  workflow_dispatch:
    inputs:
      is-stable-release:
        description: "is-stable-release: If set to false, uploads to test.pypi.org and does not create a GitHub Release."
        required: true
        type: choice
        options:
          - "true"
          - "false"
        default: "false"

jobs:
  release:
    runs-on: ubuntu-latest

    container:
      image: python:3

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          pip install poetry
          apt update
          apt install -y bison hub

      - name: Install dependencies
        run: poetry install

      - name: Build
        run: poetry build

      - name: Install built wheel into a clean env for self-test
        run: pip install dist/*.whl pytest

      - name: self-test
        run: pytest -o "addopts=" --import-mode=importlib

      - name: upload package (test.pypi.org)
        if: github.event.inputs.is-stable-release == 'false'
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish -r testpypi -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: upload package (pypi.org)
        if: github.event.inputs.is-stable-release == 'true'
        run: |
          poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish GitHub Release
        if: github.event.inputs.is-stable-release == 'true'
        run: |
          VERSION=$(poetry version -s)
          echo ${VERSION} > /tmp/message

          hub release create \
            --file /tmp/message \
            --attach dist/neologism-${VERSION}.tar.gz \
            ${VERSION}
