name: Release

on:
  workflow_dispatch:
    inputs:
      use_test_registry:
        description: Upload to test.pypi.org (true / false)
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    container:
      image: python:3

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          pip install -r requirements.txt
          pip install pytest build twine
          apt update
          apt install -y bison

      - name: build
        run: |
          python -m build

      - name: install
        run: |
          pip install dist/*.whl

      - name: self-test
        run: |
          pytest --import-mode=importlib

      - name: upload package (test.pypi.org)
        if: github.event.inputs.use_test_registry == 'true'
        run: |
          twine upload -r testpypi dist/* -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: upload package (pypi.org)
        if: github.event.inputs.use_test_registry == 'false'
        run: |
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
